[build-system]
requires = [
    "setuptools>=68",
]
build-backend = "setuptools.build_meta"

[project]
name = "OctoPrint-Telegram"
version = "1.11.0"
description = "Control your printer and receive notification messages via Telegram Messenger."
authors = [
    { name = "Jacopo Tediosi", email = "jacopotediosi@gmail.com" },
]
requires-python = ">=3.7,<4"
dependencies = [
    "pillow>=9.1",  # For Image.Transpose and Image.Resampling
    "psutil",
    "pylru>=1.1",  # For lrucache.get()
    "requests[socks]",
    "typing_extensions>=4.4",  # For typing_extensions.override
]
dynamic = [
    "license",
]

[project.entry-points."octoprint.plugin"]
telegram = "octoprint_telegram"

[project.urls]
Homepage = "https://github.com/jacopotediosi/OctoPrint-Telegram"

[project.optional-dependencies]
develop = [
    "go-task-bin",
]

[dependency-groups]
typechecking = [
    "OctoPrint==2.0.0rc5 ; python_version >= '3.9' and python_version < '3.15'",
]

[project.readme]
file = "README.md"
content-type = "markdown"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = [
    "octoprint_telegram",
    "octoprint_telegram.*",
]

[tool.ruff]
line-length = 120
fix = true

[tool.ruff.lint]
preview = true
explicit-preview-rules = true
extend-select = [
    "A", # flake8-builtins
    "ANN", # flake8-annotations
    "ARG", # flake8-unused-arguments
    "B", # flake8-bugbear
    "BLE", # flake8-blind-except
    "C4", # flake8-comprehensions
    "D", # pydocstyle
    "D420", # incorrect-section-order
    "DOC102", # docstring-extraneous-parameter
    "DOC201", # docstring-missing-returns
    "DOC202", # docstring-extraneous-returns
    "DOC402", # docstring-missing-yields
    "DOC403", # docstring-extraneous-yields
    "DOC501", # docstring-missing-exception
    "DTZ", # flake8-datetimez
    "EXE", # flake8-executable
    "FA", # flake8-future-annotations
    "G", # flake8-logging-format
    "I", # isort
    "ICN", # flake8-import-conventions
    "INP", # flake8-no-pep420
    "INT", # flake8-gettext
    "LOG", # flake8-logging
    "PIE", # flake8-pie
    "PLC", # Pylint
    "PLE", # Pylint
    "PLW", # Pylint
    "RET", # flake8-return
    "RSE", # flake8-raise
    "RUF", # Ruff-specific rules
    "S", # flake8-bandit
    "SLF", # flake8-self
    "SLOT", # flake8-slots
    "T20", # flake8-print
    "TC", # flake8-type-checking
    "UP", # pyupgrade
    "YTT", # flake8-2020
]
ignore = [
    "BLE001", # blind-except
    "D100", # undocumented-public-module
    "D101", # undocumented-public-class
    "D104", # undocumented-public-package
    "S110", # try-except-pass
    "TRY002", # raise-vanilla-class
]

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.lint.per-file-ignores]
"dev_utils/**" = [
    "INP001", # implicit-namespace-package
    "T201", # print
]
"octoprint_telegram/emoji/unicode_emoji_dict.py" = [
    "RUF001", # ambiguous-unicode-character-string
]

[tool.ruff.lint.pydoclint]
ignore-one-line-docstrings = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ty.environment]
python-version = "3.7"

[tool.djlint]
no_set_formatting=true
ignore = [
    "H021", # Inline styles should be avoided.
]

[tool.codespell]
skip = "octoprint_telegram/emoji/unicode_emoji_dict.py"
