blank_issues_enabled: false
contact_links:
  - name: ❤️ Want to sponsor this project?
    url: https://github.com/sponsors/jacopotediosi
    about: This plugin is developed by a volunteer in their spare time — please consider buying me a coffee!
